// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pb_Response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from pb_Response.proto</summary>
public static partial class PbResponseReflection {

  #region Descriptor
  /// <summary>File descriptor for pb_Response.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PbResponseReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFwYl9SZXNwb25zZS5wcm90byLjAQoLcGJfUmVzcG9uc2USLAoLc3RhdHVz",
          "X2NvZGUYASABKA4yFy5wYl9SZXNwb25zZS5TdGF0dXNDb2RlEiMKBnJlYXNv",
          "bhgCIAEoDjITLnBiX1Jlc3BvbnNlLlJlYXNvbiIyCgpTdGF0dXNDb2RlEgsK",
          "B1VOS05PV04QABIHCgJPSxDIARIOCglOT1RfRk9VTkQQlAMiTQoGUmVhc29u",
          "EggKBE5PTkUQABIZChVTT1VSQ0VfTk9UX1JFR0lTVEVSRUQQARIeChpERVNU",
          "SU5BVElPTl9OT1RfUkVHSVNURVJFRBACYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::pb_Response), global::pb_Response.Parser, new[]{ "StatusCode", "Reason" }, null, new[]{ typeof(global::pb_Response.Types.StatusCode), typeof(global::pb_Response.Types.Reason) }, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class pb_Response : pb::IMessage<pb_Response>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<pb_Response> _parser = new pb::MessageParser<pb_Response>(() => new pb_Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<pb_Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PbResponseReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb_Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb_Response(pb_Response other) : this() {
    statusCode_ = other.statusCode_;
    reason_ = other.reason_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb_Response Clone() {
    return new pb_Response(this);
  }

  /// <summary>Field number for the "status_code" field.</summary>
  public const int StatusCodeFieldNumber = 1;
  private global::pb_Response.Types.StatusCode statusCode_ = global::pb_Response.Types.StatusCode.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::pb_Response.Types.StatusCode StatusCode {
    get { return statusCode_; }
    set {
      statusCode_ = value;
    }
  }

  /// <summary>Field number for the "reason" field.</summary>
  public const int ReasonFieldNumber = 2;
  private global::pb_Response.Types.Reason reason_ = global::pb_Response.Types.Reason.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::pb_Response.Types.Reason Reason {
    get { return reason_; }
    set {
      reason_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as pb_Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(pb_Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (StatusCode != other.StatusCode) return false;
    if (Reason != other.Reason) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (StatusCode != global::pb_Response.Types.StatusCode.Unknown) hash ^= StatusCode.GetHashCode();
    if (Reason != global::pb_Response.Types.Reason.None) hash ^= Reason.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (StatusCode != global::pb_Response.Types.StatusCode.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) StatusCode);
    }
    if (Reason != global::pb_Response.Types.Reason.None) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Reason);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (StatusCode != global::pb_Response.Types.StatusCode.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) StatusCode);
    }
    if (Reason != global::pb_Response.Types.Reason.None) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Reason);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (StatusCode != global::pb_Response.Types.StatusCode.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) StatusCode);
    }
    if (Reason != global::pb_Response.Types.Reason.None) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Reason);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb_Response other) {
    if (other == null) {
      return;
    }
    if (other.StatusCode != global::pb_Response.Types.StatusCode.Unknown) {
      StatusCode = other.StatusCode;
    }
    if (other.Reason != global::pb_Response.Types.Reason.None) {
      Reason = other.Reason;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          StatusCode = (global::pb_Response.Types.StatusCode) input.ReadEnum();
          break;
        }
        case 16: {
          Reason = (global::pb_Response.Types.Reason) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          StatusCode = (global::pb_Response.Types.StatusCode) input.ReadEnum();
          break;
        }
        case 16: {
          Reason = (global::pb_Response.Types.Reason) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the pb_Response message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum StatusCode {
      [pbr::OriginalName("UNKNOWN")] Unknown = 0,
      [pbr::OriginalName("OK")] Ok = 200,
      [pbr::OriginalName("NOT_FOUND")] NotFound = 404,
    }

    public enum Reason {
      [pbr::OriginalName("NONE")] None = 0,
      [pbr::OriginalName("SOURCE_NOT_REGISTERED")] SourceNotRegistered = 1,
      [pbr::OriginalName("DESTINATION_NOT_REGISTERED")] DestinationNotRegistered = 2,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
